### ISSUE TITLE
<notype> in unexpected places

### ISSUE THREAD

**Issue by laughedelic** [scalameta/language-server#125]
![2017-12-14 00 12 57](https://user-images.githubusercontent.com/766656/33970241-49fb0588-e072-11e7-90b2-fcee44eb7abc.gif)

* `<notype>` on `class` or `final` is OK
* `<notype>`  on the class name is strange
* classes type on `extends` is weird

And in general I think we should filter out all `<notype>`s  and send empty responses instead.

**Comment by gabro** [comment]
I agree! Some of those cases can be fixed by refining the type for which we ask the type.

Just to provide some context, we can't simply ask for a type of a tree on hover. We need to handle the specific tree structure for the hover to make sense.

For instance we currently handle cases like val definitions:

```
val x = List(Some(1))
val y: List[Option[Int]] = List(Some(1)) 
```

If you hover on `x` you want to the type of its lhs (which `List[Some[Int]]`), but if you hover on `y` you want its declared type (which is `List[Option[Int]]`).

This logic is here https://github.com/scalameta/language-server/blob/87452e193986b784d7e0bad1fc2387997fa42e92/metaserver/src/main/scala/scala/meta/languageserver/providers/HoverProvider.scala#L34-L48 and can be easily extended.

> in general I think we should filter out all <notype>s and send empty responses instead.

I agree 👍

**Comment by olafurpg** [comment]
Fixed in #126

**Comment by laughedelic** [comment]
But #126 fixed only filtering out `<notype>`. This issue was more about unexpected results on keywords and missing type on the class name. But it's OK, I'll open another issue about adjusting `typeOfTree` mentioned above then.

**Comment by olafurpg** [comment]
Now that we build semanticdbs on the fly we might want to consider moving hover to use that data instead of the PC. semanticdb should handle all of the quirks from the scalac trees and if it doesn't then it's a bug.  `Denotation.signature` contains the type of a symbol, the default formatting is maybe a bit unusual. Method types look something like this `identity: [T] => (e: T): T`  iirc. That's intentional however, since it's possible to parse that into a `scala.meta.Type.Method` and print differently. We use it for example in scalafix for ExplicitResultTypes here https://github.com/scalacenter/scalafix/blob/e4a5c35d676aee196edd645a9f860330606ebfe7/scalafix-core/shared/src/main/scala/scalafix/internal/util/TypeSyntax.scala#L44-L55 All names inside signatures like `List` can optionally be resolved to their full names `scala.collection.immutable.List` etc

**Comment by laughedelic** [comment]
Sounds good to me! 👍  Types formatting can be improved/standardized later (and unified with completions/signature-help/etc.).
