### ISSUE TITLE
Signature Help request

### ISSUE THREAD

**Issue by gabro** [scalameta/language-server#20]
See [`textDocument/signatureHelp`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#signature-help-request). @olafurpg at a first glance, do you think we can pull this off using denotations only?

**Comment by olafurpg** [comment]
I think it's best to try and implement this with the presentation compiler, since you want to see the parameter list while you type arguments. If that doesn't work out, we can fix https://github.com/scalameta/scalameta/issues/1152 we will be able to convert to semanticbs on the fly and implement these features with scalameta.

**Comment by olafurpg** [comment]
I am working on this and will have a PR coming soon :)

**Comment by gabro** [comment]
This has been implemented in #51
