### ISSUE TITLE
Detection of JDK path is not reliable

### ISSUE THREAD

**Issue by gabro** [scalameta/language-server#41]
Currently we only check for the `JAVA_HOME` env variable, but that's not guaranteed to be set (
for instance it's not set on my machine)

https://github.com/scalameta/language-server/blob/984e42d720deaa280c20080a82cd73050c05e5d8/metaserver/src/main/scala/scala/meta/languageserver/CompilerConfig.scala#L47-L48

**Comment by gabro** [comment]
I think something like

https://github.com/jsdevel/node-find-java-home/blob/master/index.js

could work.

**Comment by gabro** [comment]
actually, `sys.props.get("java.home")` saves the day. I'll send a PR.

**Comment by daniil-timofeev** [comment]
Hello. The command `sys.props.get("java.home")' doesn't catch installed `java home` variable at my windows 7 machine, perhaps because the default Oracle JDK installer sets up this variable as `%JAVA_HOME%`. Changing this variable name to 'JAVA_HOME' will solve my problems, but it would be great to have an opportunity to set the `java home` path through the plugin settings. As it done in java language server, for example.

**Comment by gabro** [comment]
@daniil-timofeev that makes sense, tracking it in https://github.com/scalameta/metals/issues/210
