### ISSUE TITLE
Send log messages to client

### ISSUE THREAD

**Issue by gabro** [scalameta/language-server#85]
LSP supports sending log messages to the client, using `connection.logMessage`.
Those messages are then handled by the client in different ways, for instance VSCode displays them in the `Scalameta` output channel.

I think it would be more convenient than outputting to a file like we do now, or at least we could have both, so that one can access those logs more conveniently without leaving the editor.

**Comment by olafurpg** [comment]
We can maybe use a custom logback appender https://logback.qos.ch/manual/appenders.html to take care of this. We can then configure two appenders in logback.xml instead of only ConsoleAppender. For starters, we can probably get away with a global mutable `Notifications` object that is set by the LSP server on initialize. WDYT?

**Comment by olafurpg** [comment]
Why is this labeled "tech debt" btw? For me this is an lsp feature!

**Comment by gabro** [comment]
> Why is this labeled "tech debt" btw? For me this is an lsp feature!

My mistake!

**Comment by gabro** [comment]
> We can maybe use a custom logback appender logback.qos.ch/manual/appenders.html to take care of this. We can then configure two appenders in logback.xml instead of only ConsoleAppender. For starters, we can probably get away with a global mutable Notifications object that is set by the LSP server on initialize. WDYT?

I was thinking the same about the custom appender: It would be nice to do this without changing how we log right now.
