### ISSUE TITLE
Run on other triggered executions

### ISSUE THREAD

**Issue by cquiroz** [scalameta/language-server#98]
I'm just starting to use `language-server` with vscode so this may not be a bug.
I normally use other triggered build commands like `~fastOptJS` or `~reStart`. It seems `language-server` only updates when `~compile` or `~test` is called. Is that correct? Can it be improved?

**Comment by gabro** [comment]
Hi @cquiroz, some features of lsp depends on the generation of `.semanticdb` files. These files are generated by the `semanticdb-scalac` compiler plugin. The plugin should run whenever the compiler runs, so I think `reStart` should trigger that (I don't know about `fastOptJS` because I'm not sure of where scalajs hooks into the compiler).

What makes you say that those commands don't make the server "update"?

**Comment by cquiroz** [comment]
I keep getting a message that the code should be recompiled when running `~reStart`. My interpretation is that the editor sees that files are modified so you should recompile. If i do `~compile` I don't see that

I maybe missinterpreting things though. I have barely tested  `language-server` and plugin

**Comment by olafurpg** [comment]
@cquiroz In #116 this warning should no longer appear. The plugin will re-compile your open buffer to give up-to-date go to definition without waiting for sbt compile.

**Comment by cquiroz** [comment]
Great, thanks. I’ll test it tonight
